# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7aa7af7e487cf00c13b85c899e11338a6f9dc86c533254d2c7226b50ccb1b73f812a57e30f2b251d75b13d298b876b1eeba7bd2ff73db84d725b997d4efc97c

test:
  secret_key_base: ae561d45d3c4ea87c0ebe7a42c822f1dd6315a26035672b1f6c8ef795c884b747aed4a2efa501fe081b932927c12d52f81af5a03e00e2ea73c8812cdb37e8d7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: ae561d45d3c4ea87c0ebe7a42c822f1dd6315a26035672b1f6c8ef795c884b747aed4a2efa501fe081b932927c12d52f81af5a03e00e2ea73c8812cdb37e8d7b
